import type { FullConfig, FullResult, Reporter, TestCase, TestResult } from '@playwright/test/reporter'
import fs from 'node:fs'
import path from 'node:path'

/**
 * Writes AEOS council-style failure report for Loop Engineer handoff.
 */
class CouncilReporter implements Reporter {
  private failures: Array<{
    title: string
    error: string
    file: string
  }> = []

  onTestEnd(test: TestCase, result: TestResult) {
    if (result.status === 'failed' || result.status === 'timedOut') {
      this.failures.push({
        title: test.titlePath().join(' › '),
        error: result.error?.message?.split('\n')[0] || result.status,
        file: test.location.file,
      })
    }
  }

  async onEnd(result: FullResult) {
    const root = path.resolve(process.cwd(), '..')
    const out = path.join(root, '.kiro', 'memory', 'e2e-failure-report.md')
    fs.mkdirSync(path.dirname(out), { recursive: true })

    if (result.status === 'passed' || this.failures.length === 0) {
      fs.writeFileSync(
        out,
        `# E2E Failure Report\n\n**Status:** PASS\n\nNo failures. Loop may sign off.\n`,
        'utf8',
      )
      return
    }

    const lines = [
      '# E2E Failure Report',
      '',
      '> Generated by Playwright council reporter for `.kiro/workflows/e2e-test-loop.md`.',
      '',
      `**Status:** FAIL (${result.status})`,
      `**When:** ${new Date().toISOString()}`,
      '',
      '## Failures for Engineering Council',
      '',
      '| Test | Error | Suspected layer | Recommended engineer |',
      '|------|-------|-----------------|----------------------|',
    ]

    for (const f of this.failures) {
      const layer = guessLayer(f.error, f.title)
      lines.push(`| ${f.title.replace(/\|/g, '/')} | ${f.error.replace(/\|/g, '/').slice(0, 120)} | ${layer.layer} | ${layer.engineer} |`)
    }

    lines.push(
      '',
      '## Next actions',
      '',
      '1. Loop Engineer assigns recommended engineer(s).',
      '2. Fix root cause (do not weaken assertions without council).',
      '3. Re-run `npm run test:e2e:loop`.',
      '',
      '## Artifacts',
      '',
      '- `frontend/test-results/` (screenshots/videos)',
      '- `frontend/playwright-report/`',
      '',
    )

    fs.writeFileSync(out, lines.join('\n'), 'utf8')
  }
}

function guessLayer(error: string, title: string): { layer: string; engineer: string } {
  const e = `${error} ${title}`.toLowerCase()
  if (e.includes('econnrefused') || e.includes('net::') || e.includes('timeout') && e.includes('5173')) {
    return { layer: 'env/preview', engineer: 'Preview Engineer' }
  }
  if (e.includes('/api/') || e.includes('401') || e.includes('500') || e.includes('enrollment') && e.includes('stub')) {
    return { layer: 'backend', engineer: 'Backend Engineer' }
  }
  if (e.includes('locator') || e.includes('strict mode') || e.includes('visible') || e.includes('login')) {
    return { layer: 'frontend', engineer: 'Frontend Engineer' }
  }
  return { layer: 'unknown', engineer: 'Loop Engineer (triage)' }
}

export default CouncilReporter
